// @ts-check
import { defineConfig } from 'astro/config';
import sitemap from '@astrojs/sitemap';

export default defineConfig({
  site: 'https://www.computezap.com',
  integrations: [sitemap()],
  // Keep legacy programmatic URLs working in local dev/preview as well as
  // production. Vercel mirrors these redirects with permanent 301 rules.
  redirects: {
    '/[n]-days-from-today': '/days-from-today/[n]-days-from-today',
    '/[kg]-kg-to-lbs': '/kg-to-lbs/[kg]-kg-to-lbs',
    '/[mb]-mb-to-gb': '/mb-to-gb/[mb]-mb-to-gb',
    '/[yards]-yards-to-meters': '/yards-to-meters/[yards]-yards-to-meters',
    '/[feet]-feet-[inches]-inches-in-cm': '/height/[feet]-feet-[inches]-inches-in-cm',
    '/[x]-percent-off-[y]': '/percent-off/[x]-percent-off-[y]',
    // Category URL redirects (old flat URLs → new category/slug URLs)
    '/atm-to-bar':               '/converters/atm-to-bar',
    '/bar-to-psi':               '/converters/bar-to-psi',
    '/dwt-to-grams':             '/converters/dwt-to-grams',
    '/gallons-to-liters':        '/converters/gallons-to-liters',
    '/grain-to-mg':              '/converters/grain-to-mg',
    '/mph-to-knots':             '/converters/mph-to-knots',
    '/oz-to-pint':               '/converters/oz-to-pint',
    '/quart-to-gallon':          '/converters/quart-to-gallon',
    '/troy-ounces-to-pounds':    '/converters/troy-ounces-to-pounds',
    '/401k-calculator':          '/finance/401k-calculator',
    '/amortization-calculator':  '/finance/amortization-calculator',
    '/apr-calculator':           '/finance/apr-calculator',
    '/compound-interest-calculator': '/finance/compound-interest-calculator',
    '/cost-of-living-calculator':    '/finance/cost-of-living-calculator',
    '/roth-ira-calculator':      '/finance/roth-ira-calculator',
    '/savings-calculator':       '/finance/savings-calculator',
    '/bac-calculator':           '/health/bac-calculator',
    '/binary-to-text':           '/calculators/binary-to-text',
    '/concrete-calculator':      '/calculators/concrete-calculator',
    '/hours-in-a-week':          '/date-time/hours-in-a-week',
    '/military-time-converter':  '/date-time/military-time-converter',
    '/biweekly-mortgage-calculator':   '/finance/biweekly-mortgage-calculator',
    '/cd-calculator':                  '/finance/cd-calculator',
    '/debt-snowball-calculator':       '/finance/debt-snowball-calculator',
    '/margin-calculator':              '/finance/margin-calculator',
    '/markup-calculator':              '/finance/markup-calculator',
    '/mortgage-payoff-calculator':     '/finance/mortgage-payoff-calculator',
    '/reverse-sales-tax-calculator':   '/finance/reverse-sales-tax-calculator',
    '/celsius-to-fahrenheit':          '/converters/celsius-to-fahrenheit',
    '/cm-to-inches':                   '/converters/cm-to-inches',
    '/cups-to-gallons':                '/converters/cups-to-gallons',
    '/cups-to-tablespoons':            '/converters/cups-to-tablespoons',
    '/fahrenheit-to-celsius':          '/converters/fahrenheit-to-celsius',
    '/km-to-miles':                    '/converters/km-to-miles',
    '/knots-to-mph':                   '/converters/knots-to-mph',
    '/liters-to-gallons':              '/converters/liters-to-gallons',
    '/meters-to-feet':                 '/converters/meters-to-feet',
    '/ounces-in-a-pound':              '/converters/ounces-in-a-pound',
    '/oz-to-quarts':                   '/converters/oz-to-quarts',
    '/decimal-to-fraction':            '/calculators/decimal-to-fraction',
    '/percent-off-calculator':         '/calculators/percent-off-calculator',
    '/percentage-calculator':          '/calculators/percentage-calculator',
    '/percentage-decrease-calculator': '/calculators/percentage-decrease-calculator',
    '/percentage-increase-calculator': '/calculators/percentage-increase-calculator',
    '/pythagorean-theorem-calculator': '/calculators/pythagorean-theorem-calculator',
    '/square-footage-calculator':      '/calculators/square-footage-calculator',
    '/hours-in-a-month':               '/date-time/hours-in-a-month',
    '/hours-in-a-year':                '/date-time/hours-in-a-year',
    '/minutes-in-a-day':               '/date-time/minutes-in-a-day',
    '/seconds-in-a-year':              '/date-time/seconds-in-a-year',
    '/time-to-decimal-calculator':     '/date-time/time-to-decimal-calculator',
    '/weeks-in-a-year':                '/date-time/weeks-in-a-year',
  },
});
